### ISSUE TITLE
标题之间间隔很大

### ISSUE THREAD

**Issue by jianzs** [suziwen/markdownxiaoshujiang#1022]
请问一下，为什么标题之间的间隔这么大？有什么方法可以调整么？
![间隔很大](http://xsj.zhengsj.top/小书匠/2018年12月30日201812301546139589999.png)

**Comment by suziwen** [comment]
可以自定义 css 样式调整的

``` css
h1, h2, h3, h4, h5, h6 {
    /* margin: 1.0em 0 .6em 0; */
    margin: 0;
}
h1.story_title {
    /*margin: 0.7em 0;*/
    margin: 0;
}
```
