### ISSUE TITLE
如何修改导出的pdf中字体大小

### ISSUE THREAD

**Issue by ajinnet** [suziwen/markdownxiaoshujiang#1091]
我导出的pdf生成的字体有点太小了，怎么才可以弄大一点吗？

**Comment by suziwen** [comment]
自定义 css 样式

比如

``` css
.xsj_export_pdf{
font-size: 120%;
}
```

或者这样写

``` css
@media print{
html,body{
    font-size: 120%;
}
}
```
