### ISSUE TITLE
checkbox事项不应该划删除线

### ISSUE THREAD

**Issue by JillCheng** [suziwen/markdownxiaoshujiang#113]
删除线一般表示不要的意思,很少用来表示完成(虽然的确有这个意思,但是容易产生误导)

**Comment by suziwen** [comment]
这个预览的话,你可以自己自定义css样式把它去掉

在 `设置->基本->预览区样式`里添加

``` css
.checkbox .checked {
    text-decoration: inherit;
}
```

如果提出异议的人比较多的话,再考虑把基础样式去掉,现在暂时先不动这个.
