### ISSUE TITLE
编辑器对连字（ligature）字体的渲染问题

### ISSUE THREAD

**Issue by jackytsu** [suziwen/markdownxiaoshujiang#1228]
如果在编辑中使用了支持连字（ligature）特性的字体，比如FiraCode，输入 ~~连字字符后（比如：>=）~~ 全角的破折号（——）后，会造成光标错位。
如图所示，图中的光标实际是在文字的结尾处。
![错位截图](https://i.loli.net/2019/11/06/I9QDZlgWmFjkKqw.png)

**Comment by suziwen** [comment]
这个看着像是你在 ace 内置编辑器里使用了非等宽字体引起的。

可以在 `设置>编辑器>编辑器字体` 里设置成 `monospace` 这些等宽字体。（要求操作系统里有相应的等宽字体）

------------------

或者 也可以切换成 codemirror 编辑器，该编辑器不需要等宽字体的限制。

**Comment by jackytsu** [comment]
我使用的是“等距更纱黑体 T SC”，该字体是等宽字体。截图是我在 vs code 中使用该字体并开启“editor.fontLigatures”特性的情况（标注处是光标所在位置）：
![image](https://user-images.githubusercontent.com/608014/68350818-905e8300-013c-11ea-9055-9de8cc30db41.png)

**Comment by suziwen** [comment]
可以在 `设置>基本>全局自定义样式` 里这样设定类似下面的 css 。  （建议在 chrome 的调试工具里调试）

```` css

@font-face{
    font-family: 'Fira Code';
    src: url('https://raw.githubusercontent.com/tonsky/FiraCode/master/distr/eot/FiraCode-Regular.eot') format('embedded-opentype'),
         url('https://raw.githubusercontent.com/tonsky/FiraCode/master/distr/woff2/FiraCode-Regular.woff2') format('woff2'),
         url('https://raw.githubusercontent.com/tonsky/FiraCode/master/distr/woff/FiraCode-Regular.woff') format('woff'),
         url('https://raw.githubusercontent.com/tonsky/FiraCode/master/distr/ttf/FiraCode-Regular.ttf') format('truetype');
    font-weight: normal;
    font-style: normal;
}

#id_content_editor.ace_editor{
    -webkit-font-feature-settings: "liga" on, "calt" on;
    -webkit-font-smoothing: antialiased;
    text-rendering: optimizeLegibility;
    font-family: 'Fira Code';!important
}
.CodeMirror pre{
font-variant-ligatures: contextual;
    font-family: 'Fira Code';!important
}
.CodeMirror pre .cm-xsj_code {
font-variant-ligatures: contextual;
    font-family: 'Fira Code';!important
}
````
codemirror 编辑器效果
![image](https://user-images.githubusercontent.com/57370/68384414-86676f00-0192-11ea-8b72-27da50d9f684.png)

ace 编辑器效果

![image](https://user-images.githubusercontent.com/57370/68384671-14dbf080-0193-11ea-8a86-1827278748c1.png)

参考的链接 

https://github.com/tonsky/FiraCode/wiki/cloud9-instructions

https://github.com/tonsky/FiraCode#editor-support

-----------------

我这边只测试了下  FiraCode 字体，如果你那边按照上面的设定无法使用 `等距更纱黑体 T SC` 字体的话，可以再说一下，我再单独下载个这字体测试下。
