### ISSUE TITLE
点击左侧文件夹同步时github返回451错误

### ISSUE THREAD

**Issue by smile365** [suziwen/markdownxiaoshujiang#1238]
提示

```json
{"path":"/repos/smile365/blog/contents/","request":{"dataType":"json"},"error":451}
```

请求头   
```yaml
Request URL: https://api.github.com/repos/smile365/blog/contents/?ref=master&xxx
Request Method: GET
Status Code: 451 Unavailable for Legal Reasons
Remote Address: 13.250.94.254:443
Referrer Policy: no-referrer-when-downgrade
```
