### ISSUE TITLE
tab会让段落变成代码高亮 请问怎么解决

### ISSUE THREAD

**Issue by Yuki-J1** [suziwen/markdownxiaoshujiang#1287]
## 一、概述
越主动、技巧越熟练的阅读，效率就更高
## 阅读的目的与层次
 1. 阅读的目的
	阅读的目的大致分为两种 **==为了资讯==** 阅读 和  **==为了提高理解能力==** 阅读

		1.1 为了资讯而阅读
		“碎片化阅读”，刷微博、微信、新闻、知乎都属于这类。我们会自我感觉我们从这些资讯中获得很多知识，由此产生极大满足感。

		1.2

<p style="text-indent:2em">
	1.2
</p>

![QQ截图20200224180547](https://user-images.githubusercontent.com/41263770/75143985-15dc6200-5731-11ea-9de4-f6d08e292872.png)

tab会让段落变成代码高亮 请问怎么解决 非常感谢

**Comment by suziwen** [comment]
markdown 语法里 4 个空格就代表着代码块。tab　键输入默认是　4个空格进行替换。

想要段首两个空格的效果只能使用中文全角的空格代替(英文空两格是无效的)，或者自定义css 样式来代码段首缩进的效果。

``` css
.xsj_paragraph_level_0:before, blockquote > .xsj_paragraph_level_1:before {
    content: '　';
    display: inline-block;
    width: 2em;
}
```
