### ISSUE TITLE
查找高亮显示

### ISSUE THREAD

**Issue by AtaraxiaZ** [suziwen/markdownxiaoshujiang#1321]
使用ctrl+f查找文本时，可否将匹配文本高亮显示，现在是用个透明框框起来，会比较难找，即使每次都会出现在页面底部，但还是不够明显，如果能用荧光笔类似的高亮就更好了。

**Comment by suziwen** [comment]
可以自己先在 `设置>基本>全局自定义样式(建议熟悉 css 样式的用户使用)` 里添加下面的样式. 后继版本我再优化下.

```css
.cm-matchhighlight {
    outline: 2px solid;
    outline-offset: 2px;
    background-color: #ecec06;
}
```
