### ISSUE TITLE
发布到博客块代码不显示行号

### ISSUE THREAD

**Issue by leongfeng** [suziwen/markdownxiaoshujiang#136]
用同一篇文章测试了开源中国和博客园两个博客。发布的博客块代码不显示行号。
我直接看博客的生成的源码是这样的。
<span class="li_linenum_before_span li_linenum_before_span_hide" style="content: counter(lines , decimal); position: absolute; left: 0px; text-align: center; width: 2.5em; opacity: 0.5; vertical-align: top; display: none;">46</span>

我导出成html看源码是这样的：
<li class="li_linenum " date-linenum="46" style="line-height: 20px; margin-left: 10px; list-style: none; counter-increment: lines 1;"><span class="li_linenum_before_span li_linenum_before_span_hide" style="content: counter(lines , decimal); position: absolute; left: 0px; text-align: center; width: 2.5em; opacity: 0.5; vertical-align: top; display: none;">46</span>

li标签的后面的没贴上来。
文章开始我是直接使用是 `sql 我以为是我的问题，我又重新尝试了` sql?linenums&fancy=1,3,5 这样
，1，3，5 行的效果是出来了，但是行号还是不行。

**Comment by suziwen** [comment]
嗯，这个是已发现的bug，还没发布修正。主要原因是各个博客自己的css影响了导出的样式。

http://www.cnblogs.com/suziwen/p/5150103.html

**Comment by suziwen** [comment]
你可以自定义css临时解决

``` css
.code_linenums ol > li{
margin-left: 5px;
    list-style: inherit!important;
}
.li_linenum:before{
display:none;
}
```
