### ISSUE TITLE
8.2.0 本地pdf导出异常

### ISSUE THREAD

**Issue by thewon86** [suziwen/markdownxiaoshujiang#1383]
本地客户端pdf导出，页面设置宽度尺寸大那么一点点，导致左右两边各有一两个汉字显示不了。
![1](https://user-images.githubusercontent.com/8926553/85505736-8fbe2280-b621-11ea-833d-637a458a5d84.png)
![2](https://user-images.githubusercontent.com/8926553/85505765-9fd60200-b621-11ea-8616-82deff2843f5.png)

**Comment by suziwen** [comment]
这个像是文章内容里有宽度超过 pdf 页面设置的宽度引起的. 可以试试自定义 css 把预览区的宽度调小点

``` css
.preview.html_preview{
    width: 7.5in!important;
    max-width: 7.5in!important;
    min-width: 7.5in!important;
}
```
