### ISSUE TITLE
toc自动生成目录，发布到博客园出现多余的无序列表符号

### ISSUE THREAD

**Issue by howfars** [suziwen/markdownxiaoshujiang#1385]
这是在本地预览的样式，我希望发布到博客也是这种样式
![image](https://user-images.githubusercontent.com/24860642/86315090-d0d6b800-bc5b-11ea-9073-0d9056096e98.png)
但是发布到博客之后，出现了额外的一些无序列表的点符号，感觉不太好看...
我是从二级标题开始写的，所以第一行多了一个实心点，应该是表示一级标题吧
![image](https://user-images.githubusercontent.com/24860642/86315029-b00e6280-bc5b-11ea-87a9-51103ca8cbbd.png)
如何可以去除toc里边的这些点符号呢？

**Comment by suziwen** [comment]
贴一下你的博客文章链接地址 .

可能是你自己的博客园的样式重置了 toc 列表的显示. 需要自己在博客园页面 css 管理里调整.

**Comment by howfars** [comment]
这是地址
[剑指Offer_#27_二叉树的镜像 - Howfar's - 博客园](https://www.cnblogs.com/Howfars/p/13223544.html)

**Comment by howfars** [comment]
我找到解决办法了，
### 方法1：编辑器里边修改自定义样式
在预览区自定义样式添加
```css
.toc ul li
{
list-style-type: none;
}
```
再发布的时候就不会出现黑圆点了

### 方法2：修改博客园后台css
在**博客园后台-设置-页面定制 CSS 代码**里添加
```css
#cnblogs_post_body .toc ul li
{
list-style-type: none;
}
```
![image](https://user-images.githubusercontent.com/24860642/86335204-c7137b80-bc80-11ea-8720-eb2e3e8cdb8c.png)

这样已经发布的所有文章，渲染的时候目录中的圆点都没有了
