### ISSUE TITLE
太长的文件名会挤到下一行

### ISSUE THREAD

**Issue by Jasonwi** [suziwen/markdownxiaoshujiang#1388]
version 8.2.0
如图所示
![](https://o2-1258123310.cos.ap-beijing.myqcloud.com/images20200707072427.png)
是否可以设定超过一定字符就用`...`代替呢？

**Comment by suziwen** [comment]
你是想让文件列表这个位置出现 `...`,  我感觉这里折行更合里,反而是顶部的标题栏和右边的标题栏, 应该像你说的用 `...`

![image](https://user-images.githubusercontent.com/57370/86705614-a5cbda00-c048-11ea-876e-7bdf8f53949e.png)

**Comment by Jasonwi** [comment]
是的，我的意思就是标题栏位置的问题....



Form mobile client
在 苏滋文 <notifications@github.com>，2020年7月7日 上午11:59写道：

你是想让文件列表这个位置出现 ..., 我感觉这里折行更合里,反而是顶部的标题栏和右边的标题栏, 应该像你说的用 ...

[image]<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F57370%2F86705614-a5cbda00-c048-11ea-876e-7bdf8f53949e.png&data=02%7C01%7C%7C73d3414d125f49ac192808d8222a2ec9%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637296911848241905&sdata=uoRm4dIEWbCzMRHxjOUecNzRWV5Jv55yPNM7wBUeKkg%3D&reserved=0>

**Comment by suziwen** [comment]
还有一个顺便问一下

怎么感觉你截的图里字体都比较大, 感觉界面变得有点不协调的样子,你自己在设置里设置了全局样式,调整了字体大小了? 还是说跟显示器, 操作系统,分辨率等配置有关

下面的是我自己的截图

![image](https://user-images.githubusercontent.com/57370/86776124-881f6480-c08a-11ea-8f44-ad41258f0116.png)

**Comment by Jasonwi** [comment]
@suziwen 编辑区字体大小是16,分辨率1920x1080 125%缩放 并且一个尴尬的事实是这个问题又消失了
![Snipaste_2020-07-07_20-11-32](https://user-images.githubusercontent.com/59698185/86779889-a5563200-c08e-11ea-8b20-bee5c3b0d237.png)
另外可以指点下关于预览区主题的问题，我修改了`C:\Program\Story\app\css\preview\themes\story_papper.css`文件关于字体的部分，但是章节编号的设定通过更换不同的预览主题发现它是设定了一个默认的`-`分割符，如果参照 #930 又会带来关于`title`居中且带有编号 剩余的一级标题编号不居中仍需要修改默认模板，请问这个`-`分割符的设定是在什么位置可以修改呢？
![Snipaste_2020-07-07_20-17-17](https://user-images.githubusercontent.com/59698185/86780867-ce2af700-c08f-11ea-9e0a-87d051fc4a00.png)

**Comment by suziwen** [comment]
哦, 原来是你自己设置了 css 字体大小和缩放. 我还以为默认就是这吗大号字.

----------

会自定义 css 的话,也可以自己在 `设置>基本>全局自定义样式` 里,添加下面这段, 自己先临时解决.

```` css
.client_title_bar_mode .client_title_bar>.client_title_info {
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
  display: inline-block;
  width: 60%;
}

.client_title_bar_mode .client_title_bar > .client_title_control_buttons.ui.icon.buttons {
  background: #FDF6E3;
}
````


----------

问题自己消失是 `8.2.0` 版本取消显示本地文件路径了, 整个标题就变短了. 你把窗口调小,太长的标题还是会折行.

-----------

这个 `-` 分割符并不是通过 css 实现的, 而是使用了 `renderNumberHeading` 这个语法开关,硬编码进去的, 可以在 `设置>预览>xx标题编号规则` 里设置, 具体的教程在[这里](http://soft.xiaoshujiang.com/blog/numbered_heading/#e8a7a3e69e90e6b395e7aba0e88a82e6a087e9a298e7bc96e58fb7_13)

比如 `3 号标题规则` ,

可以从原来的

```
counter('h2');counter('h3', '%s. ');
```

改成 

```
counter('h2', '%s.');counter('h3', '%s. ');
```

就能达到你想要的效果.

---------

建议: 不太建议修改小书匠的 css 文件来修改主题, 因为升级后会覆盖掉旧的css 文件 . 可以在 `设置 >预览> 预览区自定义样式` 里添加自己的规则来覆盖默认规则.
