### ISSUE TITLE
列数多的表格会导致右侧预览显示不全，而且无法用滚动条调整

### ISSUE THREAD

**Issue by nemo95** [suziwen/markdownxiaoshujiang#1531]
![屏幕截图 2021-08-13 121740](https://user-images.githubusercontent.com/16649878/129306965-5d88f398-4fc2-4a0d-aabf-89770792fad6.png)

如图，右边水平滚动条拖到最左边也看不全

**Comment by suziwen** [comment]
可以暂时自定义css 样式调整下，

比如在 `设置>预览>预览区自定义样式` 里，添加下面内容

``` css
.preview.html_preview {
    min-width: 100%;
}
```
