### ISSUE TITLE
代码块文字加粗功能和官方说明不符

### ISSUE THREAD

**Issue by CoalBrother** [suziwen/markdownxiaoshujiang#1552]
官方文档：
![QQ截图20211001213705](https://user-images.githubusercontent.com/42676255/135629425-8272f6dc-79fe-48fc-a324-5e2094c40e1d.png)

实际效果：
![QQ截图20211001213753](https://user-images.githubusercontent.com/42676255/135629448-3ff2a722-d341-43e9-9bc3-8120c521ae6d.png)

**Comment by suziwen** [comment]
感谢反馈，

因为代码内加粗效果不是很明显，后来就改成了下面加三角形的效果，然后文档没有跟上。

后继会更新下文档。

-------

如果想实现加粗的话，可以自己通过 css, 覆盖掉这个效果，改成加粗的就可以了。

类似 css 

``` css
.xsj_code_strong {
    -webkit-text-emphasis: none;
    font-weight: bolder;
}
```
