### ISSUE TITLE
代码设置行号后，字体改变

### ISSUE THREAD

**Issue by RainbowXie** [suziwen/markdownxiaoshujiang#1574]
代码加了?linenums后，设置的字体就失效了。

**Comment by suziwen** [comment]
打开显示行号功能后， html 结构改变了，需要使用 `xiaoshujiang_pre` 这个 class 来设定。
比如:
```css
pre,.xiaoshujiang_pre{
    font-family: monospace;
}
```


自定义 css 样式后，发现不如预期，可以先在 web 版本里，打开浏览器的调试面板，调试完成后，再在客户端里设置就可以了。
