### ISSUE TITLE
珍珑网格服务器管理页面这个"按钮"可以隐藏吗

### ISSUE THREAD

**Issue by lqdflying** [suziwen/markdownxiaoshujiang#1644]
珍珑网格服务器管理页面这个"按钮"可以隐藏吗,他在软件的最下方,不是很协调,也很丑.看上去很奇怪
<img width="173" alt="1658507992163" src="https://user-images.githubusercontent.com/30266323/180485116-fc934c17-c288-4a97-aa7e-82aad411978a.png">

**Comment by suziwen** [comment]
可以在设置里，通过全局 css 样式，把这个按钮隐藏掉

``` css
.ui.button.server_store_button.icon {
    display: none!important;
    visibility: hidden!important;
}
```

![image](https://user-images.githubusercontent.com/57370/180629109-67091e07-48d3-44e6-a431-d3bad11984d1.png)
