### ISSUE TITLE
如何修改预览区标题字体大小

### ISSUE THREAD

**Issue by MandyCh** [suziwen/markdownxiaoshujiang#1657]
系统：win10 64位
当前版本: 8.10.2

预览区标题太大准备用CSS修改一下，但是关于字体大小方面一直不成功

操作：设置 -->预览 --> 预览区自定义样式 
添加内容 `h1{font-size:16px}`

结果：
在正文输入一级标题样式生效 字体大小颜色都有修改
预览区标题字体大小并没有生效 但是颜色修改又生效了
尝试使用类名`.story_title{font-size:16px}`字体大小也没有变化

没有别的设置修改 卸载了重新安装只改了这个CSS 

![image](https://user-images.githubusercontent.com/26193879/187142386-82bfbf0a-6a68-4cdd-9d7d-06172aec083e.png)

![image](https://user-images.githubusercontent.com/26193879/187148397-5ed9c182-5521-498c-9a85-674f0d3774e7.png)

期望：如何修改预览区的文字标题大小？

**Comment by suziwen** [comment]
文章主标题

```css
h1.story_title {
    font-size: 16px;
}
```

章节标题

```css
h1{
    font-size: 16px;
}
```


------

调 css 的话，可以先用浏览器访问小书匠[网页版](http://markdown.xiaoshujiang.com)，按 <kbd>f12</kbd> 进入开发者模式，这样就比较容易知道为什么有些 css 不生效了。
