### ISSUE TITLE
更改所见所得模式下的代码样式

### ISSUE THREAD

**Issue by liuyiwei521** [suziwen/markdownxiaoshujiang#1666]
所见所得的功能超级棒,但是所见所得区域的代码的字体有点不舒服,能否自定义

**Comment by suziwen** [comment]
到　`小书匠主按钮>设置>基本>全局自定义样式`　里，添加类似下面的 css

``` css
.cm-xsj_code, .cm-xsj_fence_code, pre.xsj_fence-code.CodeMirror-line {
    font-family: "字体名称", monospace;
}
```

将字体名称替换成你想使用的字体．
