### ISSUE TITLE
预览模式的字体怎么设置

### ISSUE THREAD

**Issue by sure-it** [suziwen/markdownxiaoshujiang#217]
问个问题，预览模式的字体有没有什么方式可以进行修改，谢谢

**Comment by suziwen** [comment]
`设置>基本>预览区自定义样式` 通过自定义 css 来修改

``` css
body {
    font-family: 'Helvetica Neue', Helvetica, Tahoma, Arial, 'Hiragino Sans GB', STHeiti, "Microsoft YaHei", "微软雅黑", 'WenQuanYi Micro Hei', STXihei, "华文细黑", Heiti, "黑体", SimSun, "宋体", Song, sans-serif;
}
```
