### ISSUE TITLE
图片对齐方式

### ISSUE THREAD

**Issue by xnnzh** [suziwen/markdownxiaoshujiang#363]
请问图片默认的对齐方式是居中的吗？怎么取消居中啊

**Comment by suziwen** [comment]
不要让图片变成块块级图片就行。就是图片上下不要有空白行的出现。

```
文字
![](图片地址)
文字
```

或者也可以自定义 css

``` css
.story_image_container {
    text-align: initial;
}
```

如果不想显示块级图片下面的标题，可以到 `设置>预览` 里把 `是否自动填充块级图片标题` 选项去掉。

![image](https://cloud.githubusercontent.com/assets/57370/24906084/0527777e-1e7c-11e7-8546-dee6a5cf40c6.png)

或者 再添加个自定义 css

```css
.story_image_container {
    text-align: initial;
}
.story_image_caption {
    display:none;
}
```
