### ISSUE TITLE
checkbox导入到印象笔记异常

### ISSUE THREAD

**Issue by ghost** [suziwen/markdownxiaoshujiang#400]
我再试图用小书匠绑定印象笔记的时候发现，在小书匠中- [ ] 是待完成，- [x]   ##是已完成；可是在印象笔记或者其他的markdown语法中[ ], [x]分别是待完成和已完成。所以再导入到印象笔记中不仅会有checkbox，还会因为前面的'-'而多了一个无序列表的标志....

**Comment by suziwen** [comment]
这个语法是参照 github 的 checkbox 的

```
- [ ] 未完成
- [x] 完成
```

- [ ] 未完成
- [x] 完成

生成的 html 结构都是  `li` 标签包裹的

``` html
<li class="task-list-item"> 未完成</li>
```

如果想导出到印象笔记里不让它有无序列表的样式，可以自定义 css

``` css
.task-list-item{
list-style-type: none!important;
}
```
