### ISSUE TITLE
预览的字体能和设置的编辑里面的字体一致吗？

### ISSUE THREAD

**Issue by ilaziness** [suziwen/markdownxiaoshujiang#418]
不一致的话，左边编辑框和右边预览感觉有点格格不入。

**Comment by suziwen** [comment]
预览的字体需要自己通过 css 来设定

比如 

``` css
body {
    font-family: Georgia,"Times New Roman",Times,"楷体","AR PL UKai CN", "NSimSun","Songti SC","SimSun",serif;
}
```
