### ISSUE TITLE
同步evernote后代码段样式不一致的问题

### ISSUE THREAD

**Issue by blurm** [suziwen/markdownxiaoshujiang#438]
赞一下小书匠，功能太强大了，今天试用了下，发现几点搞不明白的地方

版本：linux 3.1.1
小书匠客户端样式：
![xiaoshujiang1](https://user-images.githubusercontent.com/10203631/27509881-f2b3c8c0-5938-11e7-839c-bfb4aeebcb56.png)
印象笔记web端样式：
![xiaoshujiang2](https://user-images.githubusercontent.com/10203631/27509883-fd192eb8-5938-11e7-9228-cb004f909746.png)

做的唯一改动就是下面这段自定义的css了，是用markdown here的样式改过来的，这段样式在马克飞象里也试了下好像没什么明显的问题

另外在用codemirror的时候，如果选择了高亮选中行，会把光标挡住，导致看不清光标在哪里

```css
/*
 * NOTE:
 * - The use of browser-specific styles (-moz-, -webkit-) should be avoided.
 *   If used, they may not render correctly for people reading the email in
 *   a different browser than the one from which the email was sent.
 * - The use of state-dependent styles (like a:hover) don't work because they
 *   don't match at the time the styles are made explicit. (In email, styles
 *   must be explicitly applied to all elements -- stylesheets get stripped.)
 */

/* This is the overall wrapper, it should be treated as the `body` section. */
.markdown-here-wrapper {
}

/* To add site specific rules, you can use the `data-md-url` attribute that we
   add to the wrapper element. Note that rules like this are used depending
   on the URL you're *sending* from, not the URL where the recipient views it.
*/
/* .markdown-here-wrapper[data-md-url*="mail.yahoo."] ul { color: red; } */

pre, code {
  font-size: 1em;
  font-family: Consolas, Inconsolata, Courier, monospace;
}

code {
  margin: 0 0.15em;
  padding: 0.15em 0.3em;
  white-space: pre-wrap;
  background-color: #f9f2f4;
  color: #d14;
  border-radius: 4px;
  display: inline; /* added to fix Yahoo block display of inline code */
}

pre {
  font-size: 1em;
  line-height: 1.2em;
}

pre code { /* this if for code block */
  white-space: pre;
  overflow: auto; /* fixes issue #70: Firefox/Thunderbird: Code blocks with horizontal scroll would have bad background colour */
  border-radius: 6px;
  border: 1px solid #CCC;
  padding: 0.5em 0.7em;
  display: block !important; /* added to counteract the Yahoo-specific `code` rule; without this, code blocks in Blogger are broken */
}

/* In edit mode, Wordpress uses a `* { font: ...;} rule+style that makes highlighted
code look non-monospace. This rule will override it. */
.markdown-here-wrapper[data-md-url*="wordpress."] code span {
  font: inherit;
}

/* Wordpress adds a grey background to `pre` elements that doesn't go well with
our syntax highlighting. */
.markdown-here-wrapper[data-md-url*="wordpress."] pre {
  background-color: transparent;
}

/* This spacing has been tweaked to closely match Gmail+Chrome "paragraph" (two line breaks) spacing.
Note that we only use a top margin and not a bottom margin -- this prevents the
"blank line" look at the top of the email (issue #243).
*/
p {
  /* !important is needed here because Hotmail/Outlook.com uses !important to
     kill the margin in <p>. We need this to win. */
  margin: 0 0 1.2em 0 !important;
}

table, pre, dl, blockquote, q, ul, ol {
  margin: 1.2em 0;
}

ul, ol {
  padding-left: 2em;
}

li {
  margin: 0.5em 0;
}

/* Space paragraphs in a list the same as the list itself. */
li p {
  /* Needs !important to override rule above. */
  margin: 0.5em 0 !important;
}

/* Smaller spacing for sub-lists */
ul ul, ul ol, ol ul, ol ol {
  margin: 0;
  padding-left: 1em;
}

/* Use Roman numerals for sub-ordered-lists. (Like Github.) */
ol ol, ul ol {
  list-style-type: lower-roman;
}

/* Use letters for sub-sub-ordered lists. (Like Github.) */
ul ul ol, ul ol ol, ol ul ol, ol ol ol {
  list-style-type: lower-alpha;
}

dl {
  padding: 0;
}

dl dt {
  font-size: 1em;
  font-weight: bold;
  font-style: italic;
}

dl dd {
  margin: 0 0 1em;
  padding: 0 1em;
}

blockquote, q {
  border-left-width: 10px;
  border-top-right-radius: 5px;
  border-bottom-right-radius: 5px;
  border-left: 10px solid #e7ecee;
  background-color: #f2f4f6;
  padding-top: 16px;
  padding-right: 20px;
  padding-bottom: 1px;
  padding-left: 20px;
  color: #2c3f51;
  quotes: none;
}

blockquote::before, blockquote::after, q::before, q::after {
  content: none;
}

h1, h2, h3, h4, h5, h6 {
  margin: 1.3em 0 1em;
  padding: 0;
  font-weight: bold;
  color: #2c3f51
}

h1 {
  font-size: 1.6em;
  border-bottom: 5px solid #2c3f51;
}

h2 {
  font-size: 1.4em;
  border-bottom: 2px solid #a3b3cc;
}

h3 {
  font-size: 1.3em;
}

h4 {
  font-size: 1.2em;
}

h5 {
  font-size: 1em;
}

h6 {
  font-size: 1em;
  color: #777;
}

table {
  padding: 0;
  border-collapse: collapse;
  border-spacing: 0;
  font-size: 1em;
  font: inherit;
  border: 0;
}

tbody {
  margin: 0;
  padding: 0;
  border: 0;
}

table tr {
  border: 0;
  border-top: 1px solid #CCC;
  background-color: white;
  margin: 0;
  padding: 0;
}

table tr:nth-child(2n) {
  background-color: #F8F8F8;
}

table tr th, table tr td {
  font-size: 1em;
  border: 1px solid #CCC;
  margin: 0;
  padding: 0.5em 1em;
}

table tr th {
 font-weight: bold;
  background-color: #F0F0F0;
}

a {
    color: #1980e6;
    text-decoration: none;
}

strong { font-weight: bold; color: #286094;}
```

**Comment by blurm** [comment]
补充下，有时候设置里是勾选了“试用预览区系统内置样式”的，但是显示的预览样式仍然是我自定义的样式。似乎不是太稳定

**Comment by suziwen** [comment]
设置里的自定义预览确实有 bug, 需要重启后才能生效。不然实时预览显示的样式逻辑会乱。

目前自定义 css 的设计方案是

系统内置预览 css +  代码高亮 css + 用户全局自定义 css + 当前文章自定义 css

按照这个逻辑去调整就可以。禁用系统内置 css 并不能禁掉系统提供的代码高亮 css, 需要自己在 `预览区代码高亮样式` 里， 选择 `禁用代码高亮 css`

![image](https://user-images.githubusercontent.com/57370/27513922-c7d95c5e-593e-11e7-9fc6-2eab9ac7c7a8.png)

还有一个要注意的是自定义的 css 最好不要用伪元素，不然生成到印象笔记里对应的伪元素会无法生效

`selector:before{}`

**Comment by blurm** [comment]
感谢及时回复。

所以`是否使用预览区系统内置样式`这个选项该怎样理解？
勾选了的话，用户在预览区自定义样式里的内容就会失效么？

我测试的结果，不选这个选项可以正常显示用户自定义样式，勾选了之后反倒是乱七八糟了

**Comment by suziwen** [comment]
勾选后重启呢？

一般如果没有使用系统内置的 css , 新建的文章显示效果会变成这样  

![image](https://user-images.githubusercontent.com/57370/27514283-c0229450-594b-11e7-9bc1-2af5e2b4b029.png)

如果使用内置的 css , 新建文章的标签就有灰色背景的效果

![image](https://user-images.githubusercontent.com/57370/27514291-1270d046-594c-11e7-8a13-18ae286eb35c.png)

**Comment by blurm** [comment]
未勾选
![xsk11](https://user-images.githubusercontent.com/10203631/27514372-1f9203a2-59bb-11e7-86b1-65795a88a6c0.png)
勾选后
![xsk12](https://user-images.githubusercontent.com/10203631/27514374-265b7b3c-59bb-11e7-9cfc-edea11e1c018.png)

不管哪种情况，都没有正常显示系统的默认样式

**Comment by suziwen** [comment]
勾选后，你给的图，内置 css 是生效的

![image](https://user-images.githubusercontent.com/57370/27514394-e50ae710-594e-11e7-93a7-5334f8e33830.png)

你说的"没有正常显示系统的默认样式" 是指哪块样式跟 未勾选 的一样？

**Comment by blurm** [comment]
那是我理解错误了，我以为只要填了用户自定义的css内容，系统内置样式就会整个失效。

所以是用户自定义样式会覆盖到系统内置样式的相同设置项上？系统内置样式是一直生效的？

**Comment by suziwen** [comment]
默认是这样

```
系统内置预览 css + 代码高亮 css + 用户全局自定义 css + 当前文章自定义 css
```
如果用户去掉了选项 `是否使用预览区系统内置样式`

最终的结果是
```
代码高亮 css + 用户全局自定义 css + 当前文章自定义 css
```

如果用户再禁用代码高亮css选项 ![](https://user-images.githubusercontent.com/57370/27513922-c7d95c5e-593e-11e7-9fc6-2eab9ac7c7a8.png)

最终生成的 css 结果是

```
用户全局自定义 css + 当前文章自定义 css
```

**Comment by blurm** [comment]
对对，是这样的。

当前文章自定义css 是指？

**Comment by suziwen** [comment]
当前文章自定义css 在每篇文章的预览区里

![image](https://user-images.githubusercontent.com/57370/27514448-441670c0-5950-11e7-8b1b-cf23d3facd1c.png)
的这个按钮里 
![image](https://user-images.githubusercontent.com/57370/27514451-533d051e-5950-11e7-804c-2f1292966c46.png)


它只对当前文章有效。

**Comment by blurm** [comment]
了解了，功能实在是。。太太全了。

另外用户自定义样式里，设置tr的颜色有些问题，单数行的颜色无法被自定义设置覆盖。
比如，自定义样式：
```css
table tr {
  background-color: red;
}
```
![xsk13](https://user-images.githubusercontent.com/10203631/27514475-4374ebf6-59be-11e7-88db-e6fb042e8ede.png)

这个我需要单独提交个issue么？

**Comment by suziwen** [comment]
不用，就直接在这里讨论。

这个是 css 优先级及 tr, td 方面需要考虑的，属于 html + css 知识范畴

你可以在 web 版本里，通过  chrome 的 dev-tool ,看到具体的原因

![image](https://user-images.githubusercontent.com/57370/27514519-af447b2e-5952-11e7-98e6-3c7807e76ee3.png)


被内置的 td css 遮住了

需要自己再加上

``` css
.table-striped tbody > tr:nth-child(odd) > td, .table-striped tbody > tr:nth-child(odd) > th {
    background-color: initial;
}
```

**Comment by blurm** [comment]
辛苦了，我对html和css样式还真是一知半解。我先用其他配色规避下吧，有空再研究下。

感谢这么详细的解答，真是款强大的工具，由衷希望能越做越好

**Comment by blurm** [comment]
还有个小建议，代码段的行号可否选个暗点的颜色，现在的纯白色太突兀太亮了感觉

**Comment by suziwen** [comment]
代码段的行号？你是指预览区代码段的行号？

这个可以自定义 css

``` css
.li_linenum:before, .li_linenum_before_span{
color: red;
}
```

或者 

``` css
.li_linenum:before, .li_linenum_before_span{
opacity: 0.5;
}
```

第二种方案，在打印 pdf 时行号会模糊

需要注意的是导出到印象笔记时使用了 `ol + li` 默认的格式， 所以行号的样式是无法在印象笔记里生效的。（后继会再改进）
