### ISSUE TITLE
怎么改变导出的代码字体大小

### ISSUE THREAD

**Issue by weichaolin** [suziwen/markdownxiaoshujiang#468]

**Comment by suziwen** [comment]
自定义 css

你是要导出 html, 还是导出 pdf, 或者导出到其他第三方平台？

贴个图看看你现在的效果

**Comment by weichaolin** [comment]
导出到印象笔记，我用的是Xcode样式

**Comment by weichaolin** [comment]
pre
{
font-size: 16px
}
为什么16导出之后字体大小是14，14导出的字体是12

**Comment by suziwen** [comment]
``` css
body code, body .xiaoshujiang_code
{
font-size: 16px
}
```

因为默认的定义是 `90%`
