### ISSUE TITLE
网页版编辑器正文缩进无效

### ISSUE THREAD

**Issue by wadecoding** [suziwen/markdownxiaoshujiang#498]
Mac版chrome下，编辑正文时缩进不能显示
```markdown
# head1
内容
    想缩进显示的内容
```
截图上传不了，写了个代码块代替一下。其中缩进的部分不能正常显示，不知道是怎么回事

**Comment by suziwen** [comment]
这个是　markdown 语法的原因，直接忽略开头空白符号。

想要缩进的话，可以使用中文全角的空白符号

```
# head1
内容
　　欢迎使用 **{小书匠}(xiaoshujiang)编辑器**，您可以通过==设置==里的修改模板来改变新建文章的内容。
```

--------------

或者自定义 css 样式，　参考这里的讨论 #92

``` css
.preview>p{
  text-indent:2em;
  }
p .mathjax>.MathJax_SVG{
text-indent:0;
}
```
