### ISSUE TITLE
转为PDF格式时， 标题会缩进

### ISSUE THREAD

**Issue by GuoBenyi** [suziwen/markdownxiaoshujiang#509]
如 
## test 
转为 PDF 格式 时 test 会缩进，怎么取消缩进

**Comment by suziwen** [comment]
给些更详细的信息，或者贴个图看一下你说的缩进情况具体指什么。

**Comment by GuoBenyi** [comment]
详细信息我发到你的这个邮箱了，不知道你能不能收到
suziwen/markdownxiaoshujiang <markdownxiaoshujiang@noreply.github.com>

**Comment by GuoBenyi** [comment]
![default](https://user-images.githubusercontent.com/16427893/29872176-099d301e-8dc1-11e7-839e-ecb7f5cae496.png)

**Comment by suziwen** [comment]
自定义 css 可以暂时解决下

``` css
.xiaoshujiang_element.xsj_anchor {
    position: absolute;
}
```
这个算是 bug，下个版本再修复下。

-------

想要和预览区基本一样的话，可以选择 `导出 >打印 ` ，同样可以生成 pdf, 这个就是使用浏览器自带的 pdf 打印功能。
