### ISSUE TITLE
如何更改高亮语法的默认颜色

### ISSUE THREAD

**Issue by mxxiv** [suziwen/markdownxiaoshujiang#541]
在新增功能中：高亮语法支持指定颜色, ==红色 #ea0c2e==
如果我想一直都使用红色，可不可以更改默认的高亮颜色为红色呢

**Comment by suziwen** [comment]
这个可以通过自定义 css 来实现，
类似于这样
``` css
.mark{
    background-color: rgba(221, 243, 231, 0.4);
   color: #29754d;
}
```
