### ISSUE TITLE
点击预览区目录会使预览区变成空白

### ISSUE THREAD

**Issue by mxxiv** [suziwen/markdownxiaoshujiang#543]
使用[TOC]生成目录，在右侧的预览区点击目录中的某一个条目不能跳转到对应的内容位置，而且会使整个预览区变成空白。小书匠版本4.0.0。

**Comment by zmcui** [comment]
这个问题有方法处理么，还是要等新版本

**Comment by suziwen** [comment]
window 版本的话，可以自己改下 js, 和 css 文件

js 文件, `安装目录/app/js/app.js`
搜索 `<div class="xiaoshujiang_element xsj_anchor" style="position: absolute;">` , 把它改成 `<div class="xiaoshujiang_element xsj_anchor">`

css 文件, `安装目录/app/css/preview/default.css`
在文件结尾添加

```css
@media print{
  .xiaoshujiang_element.xsj_anchor{
    position: absolute;
  }
}
```
