### ISSUE TITLE
能否增加pdf正文字体设置？

### ISSUE THREAD

**Issue by everdom** [suziwen/markdownxiaoshujiang#547]
现在导出pdf时只能设置封面，页眉页脚，水印的字体，但是无法设置pdf正文字体呢，能否增加正文字体设置呢？

**Comment by suziwen** [comment]
正文的内容需要自己通过自定义 css 样式来实现。

类似

``` css
body{
font-family: "Microsoft YaHei";
font-size: 2em;
}
```

如果只想针对 pdf 打印，不想改变原有的预览样式，也可以这样设置 

``` css
@media print{
body{
font-family: "Microsoft YaHei";
font-size: 2em;
}
}
```

需要注意的是 pdf 联网打印不支持 css 字体回调，只能单独字体指定。

还有就是不支持中文字体名称 ，需要指定英文字体名称，比如 `微软雅黑` 需要使用它的英文字体名称 `Microsoft YaHei`
