### ISSUE TITLE
最新版（6.7.5.5825）印象笔记支持不好，望解决

### ISSUE THREAD

**Issue by lingjie2098** [suziwen/markdownxiaoshujiang#574]
IOC无法层次排列，无法点击跳转
![image](https://user-images.githubusercontent.com/15832370/31426734-2538bcd4-ae97-11e7-9bee-a93d0a56ae72.png)

**Comment by suziwen** [comment]
可以试试自定义 css, 不过有的小问题，就是在小书匠预览里是缩进 40px, 在印象笔记 web 版本或者他们家的客户端,缩进是 20px.

``` css
.toc ul, .toc ol {
margin-left: 20px;
}
.toc li {
margin-left: 20px;
}
```
