### ISSUE TITLE
表格宽度

### ISSUE THREAD

**Issue by sunweilibo** [suziwen/markdownxiaoshujiang#579]
```
设置          |值           |说明
--------------|------------|--------------------------------------
| fullscreen|yes或no|表示浏览器窗口是否最大化，仅限IE
|height       |数值      |表示新窗口的高度。不能小于100
|left            |数值       |表示新窗口的左坐标。不能是负值
```
![qq 20171016233112](https://user-images.githubusercontent.com/19649955/31620562-26d4083c-b2ca-11e7-950f-06958b0ef247.jpg)
请问如何使第一行显示在一行而不换行

**Comment by suziwen** [comment]
需要通过自定义 css 来控制

**Comment by sunweilibo** [comment]
有什么建议吗有什么建议吗

**Comment by suziwen** [comment]
比如对所有表格
```css
table>thead>tr>th{
   white-space: nowrap;
}
```

----------------

如果只是想针对指定表格里某一个单元格进行控制，需要在表格里使用 class

``` markdown
|<!-- {.nowrap} -->不折行|  默认 |
| -------- | ------ |
|     aaa     |   bbb     |
|     ccc     |<!-- {.redbg} --> 红色背景   |
```
然后自定义 css

```css
.nowrap{
white-space: nowrap;
}
.redbg{
background-color: red;
}
```
