### ISSUE TITLE
导出带表格的pdf格式会乱

### ISSUE THREAD

**Issue by oska874** [suziwen/markdownxiaoshujiang#60]
如果文档里面有一个表格
AA|bb
:--|:--
BB|cc
CC|dd
...

这个表格在导出的时候如果跨页，那么第二页的表格内容和表头会重叠

**Comment by oska874** [comment]
导出word 的话，表格就不会出现同样的问题

**Comment by jianrock** [comment]
遇到同样问题，导出html没有问题，但是pdf已经影响浏览了。

**Comment by suziwen** [comment]
可以自字义 css 

``` css
tr { page-break-inside: avoid; }
```

https://github.com/wkhtmltopdf/wkhtmltopdf/issues/2679
