### ISSUE TITLE
toc以及正文标题添加序号

### ISSUE THREAD

**Issue by sjm111** [suziwen/markdownxiaoshujiang#610]
您好，我想给正文标题以及toc添加序号，例如：
1. 一级标题  
1.1 二级标题  
1.1.1 三级标题
这个样式怎么添加？

**Comment by suziwen** [comment]
需要自定义 css 样式 
可以参考[这个](https://github.com/suziwen/blogxiaoshujiang/blob/master/2017-9-24%20%E5%B0%8F%E4%B9%A6%E5%8C%A0%20pdf%20%E5%AF%BC%E5%87%BA%E8%87%AA%E5%AE%9A%E4%B9%89%20css%20%E6%95%99%E7%A8%8B.md)

``` css
body {counter-reset: h1}
  h1{counter-reset: h2}
  h2 {counter-reset: h3}
  h3 {counter-reset: h4}
  h4 {counter-reset: h5}
  h5 {counter-reset: h6}

  h1:before {counter-increment: h1; content: counter(h1, cjk-ideographic) "、 "}
  h2:before {counter-increment: h2; content: counter(h2) ". "}
  h3:before {counter-increment: h3; content: counter(h2) "." counter(h3) ". "}
  h4:before {counter-increment: h4; content: counter(h2) "." counter(h3) "." counter(h4) ". "}
  h5:before {counter-increment: h5; content: counter(h2) "." counter(h3) "." counter(h4) "." counter(h5) ". "}
  h6:before {counter-increment: h6; content: counter(h2) "." counter(h3) "." counter(h4) "." counter(h5) "." counter(h6) ". "}

  
  h1.story_title:before,h2.nocount:before, h3.nocount:before, h4.nocount:before, h5.nocount:before, h6.nocount:before { content: ""; counter-increment: none } 

```

**Comment by sjm111** [comment]
嗯嗯，这个可以给正文添加，toc的序号添加呢？我前端不好~谢谢亲啦

**Comment by suziwen** [comment]
``` css
.toc ul ul {
  counter-reset: section; 
  list-style-type: none;
}
.toc ul ul>li>a:before {
  counter-increment: section; 
  content: counters(section, ".") " "; 
}


.toc>ul {
  counter-reset: sectioncjk;
  list-style-type: none;
}
.toc>ul>li>a:before {
  counter-increment: sectioncjk; 
  content: counters(sectioncjk, ".", cjk-ideographic) "、 "; 
}
```
