### ISSUE TITLE
在预览区点击目录，界面就会出错

### ISSUE THREAD

**Issue by oska874** [suziwen/markdownxiaoshujiang#65]
在预览区点击目录，界面就会出错，页面最底下会变成启动时的图案。小书匠的菜单栏看不到了，只能缩小页面才能看到菜单栏。

**Comment by suziwen** [comment]
1.6.1版本已经修复

**Comment by oska874** [comment]
能简单的说一下是什么原因吗？比较好奇

**Comment by suziwen** [comment]
应该是浏览器chrome(webkit)类的一个bug吧,在firefox是不会有这样效果的,我只是再处理了一下做了兼容.

你可以审查元数,然后定位到 '.pusher_background' ,把它的css里

``` css
.pusher_background {
  display: none;
}
```

注释掉,再点击预览里的目录,效果就又会变成你提的bug的效果了.
