### ISSUE TITLE
预览区 单行代码高亮问题

### ISSUE THREAD

**Issue by chen729223605** [suziwen/markdownxiaoshujiang#711]
用了 单行`code`的格式来高亮单行代码，预览的效果是背景有点加灰色，字的颜色还是黑色，这样不能突出文字中的代码或者一些特殊的字符串。 请问这个字体的颜色如何设置，我不懂css，如果可以改，希望能够直接提供css代码。 刚看到#703也有同样的问题， 我想要#703右边的那种样式，能够明确区分单行代码的颜色。不知可行否。 
```
`code` 
```

`code`

**Comment by suziwen** [comment]
``` css
code {
    color: #c7254e;
    background-color: #f9f2f4;
    border-radius: 4px;
}
```

**Comment by chen729223605** [comment]
谢谢 好了

**Comment by ygqygq2** [comment]
![image](https://user-images.githubusercontent.com/17672440/62098911-eced0f00-b2be-11e9-83e5-84f65ac7971c.png)

在预览区自定义样式设置后，代码块颜色也影响了。背景色取消才行

```css
code {
    color: #c7254e;
    background-color: #f9f2f4;
    border-radius: 4px;
}
```

**Comment by suziwen** [comment]
可以这样写

```
code:not(.hljs) {
    color: #c7254e;
    background-color: #f9f2f4;
    border-radius: 4px;
}
```

**Comment by suziwen** [comment]
@ygqygq2 

可以这样写

```css
code:not(.hljs) {
    color: #c7254e;
    background-color: #f9f2f4;
    border-radius: 4px;
}
```
