### ISSUE TITLE
代码块预览时上面的折叠，查看原文等选项可否设置取消显示

### ISSUE THREAD

**Issue by qgyhd1234** [suziwen/markdownxiaoshujiang#765]
有些文件里看上去怪怪的

**Comment by suziwen** [comment]
这个保存到其他存储或者导出html时，就自动没有的。

**Comment by qgyhd1234** [comment]
导出后是没有，但是用小书匠预览的时候怪怪的

**Comment by suziwen** [comment]
可以通过自定义 css 样式把它隐藏掉

``` css
.preview .xiaoshujiang_code_container>.xiaoshujiang_code_buttons{
display: none;
}
```
