### ISSUE TITLE
关于标记高亮的建议

### ISSUE THREAD

**Issue by bigsongeth** [suziwen/markdownxiaoshujiang#778]
一直都是绿色感觉不习惯。建议红色或金黄色作为默认颜色。
或者可以尝试在设置中允许修改标记高亮的首选项
或者可以尝试像富文本编辑器的给出多个标准色按钮

真的每次都要改颜色，太低效了。
谢谢您~~~嘿嘿

**Comment by suziwen** [comment]
自定义 css 样式

``` css
.mark {
background-color: rgba(219, 40, 40, 0.36);
color:  red;
}
```
