### ISSUE TITLE
PPT模式下，如何设置全局的PPT背景颜色？

### ISSUE THREAD

**Issue by JunHong1995** [suziwen/markdownxiaoshujiang#863]
目前，可以很方便的设置每一页幻灯片的颜色。但是当我需要所有幻灯片的颜色，都是同一个颜色的时候，目前的操作有些繁琐（需要在每个幻灯片前加颜色的代码），有没有一种方法可以只需要配置一下，让所有的幻灯片的背景颜色都是同一个颜色？

**Comment by suziwen** [comment]
自定义 css 样式

``` css
.reveal .slide-background {
    background-color: red;
}
```
