### ISSUE TITLE
关于引用字体设置的问题

### ISSUE THREAD

**Issue by pancong520** [suziwen/markdownxiaoshujiang#915]
你好，请问引用区域的字体样式可以修改么，可以的话给一个css样式可否？谢谢。

**Comment by suziwen** [comment]
``` css
.blockquote{
 font-family: "Microsoft YaHei", "微软雅黑"
}
```
