### ISSUE TITLE
请问支持标题带编号发布吗

### ISSUE THREAD

**Issue by zq1997** [suziwen/markdownxiaoshujiang#930]
在设置《自定义预览区样式》里添加css
``` css
body {
    counter-reset: h1
}

h1 {
    counter-reset: h2
}

h2 {
    counter-reset: h3
}

h3 {
    counter-reset: h4
}

h1:before {
    counter-increment: h1;
    content: counter(h1) ". "
}

h2:before {
    counter-increment: h2;
    content: counter(h1) "." counter(h2) ". "
}

h3:before {
    counter-increment: h3;
    content: counter(h1) "." counter(h2) "." counter(h3) ". "
}

h4:before {
    counter-increment: h4;
    content: counter(h1) "." counter(h2) "." counter(h3) "." counter(h4) ". "
}
```
可以实现预览的标题带编号，可是发布到印象就不见了，请问有这方面的支持吗

**Comment by suziwen** [comment]
这个主要是印象笔记不支持`:before`语法引起的。暂时还没想到好的解决方案。

**Comment by zq1997** [comment]
发现确实:before用不了，我现在改成用颜色来区分了，分享一下如果小伙伴要用的话
``` css
h1 { font-weight:bold; color:#d50000; font-size:200%; text-align:center; }
h2 { font-weight:bold; color:#6200ea; font-size:175%; text-align:center; }
h3 { font-weight:bold; color:#00c853; font-size:150%; text-indent:2em; }
h4 { font-weight:bold; color:#ff6d00; font-size:125%; text-indent:2em; }
h5 { font-weight:bold; color:#00b8d4; font-size:115%; text-indent:2em; }
h6 { font-weight:bold; color:#808000; font-size:105%; text-indent:2em; }
```
