### ISSUE TITLE
PPT 能左对齐么？

### ISSUE THREAD

**Issue by jianzs** [suziwen/markdownxiaoshujiang#937]
PPT模式默认是所有项目居中，但是，有些排版这样看起来不舒服，有地方可以设置为左对齐么？

**Comment by suziwen** [comment]
自定义 css 样式

比如这个

``` css
.reveal .slides {
    margin: auto 20px;
    text-align: initial;
}
```
